#ifndef DESPEC_ARRAY_SIZES
#define DESPEC_ARRAY_SIZES

#define FINGER_TAMEX_MODULES 4
#define FINGER_TAMEX_HITS    512

#define FATIMA_TAMEX_MODULES 4
#define FATIMA_TAMEX_HITS 256

#define bPLASTIC_TAMEX_MODULES 4
#define bPLASTIC_TAMEX_HITS 256

#endif /* DESPEC_ARRAY_SIZES */
