#ifndef DESPEC_ARRAY_SIZES
#define DESPEC_ARRAY_SIZES

#define FINGER_TAMEX_MODULES 4
#define FINGER_TAMEX_HITS    512

#define FATIMA_TAMEX_MODULES 1
#define FATIMA_TAMEX_HITS 256
#define FATIMA_TAMEX_CHANNELS 16

#define bPLASTIC_TAMEX_MODULES 3
#define bPLASTIC_TAMEX_HITS 256
#define bPLASTIC_TAMEX_CHANNELS 32

#define GALILEO_MAX_DETS 12
#define GALILEO_CRYSTALS 3
#define GALILEO_MAX_HITS (GALILEO_MAX_DETS * GALILEO_CRYSTALS)
#define GALILEO_FEBEX_MODULES 2

#endif /* DESPEC_ARRAY_SIZES */
